// Status transitions mapping

export const permittedTransitions = {
    DRAFT: ['CANCELLED', 'ISSUED'],
    CANCELLED: ['DRAFT'],
    ISSUED: ['REJECTED', 'ACCEPTED'],
    REJECTED: ['ISSUED'],
    ACCEPTED: ['PAYMENTSCHEDULED', 'PAYMENTCLOSED'],
    PAYMENTSCHEDULED: ['PAYMENTSENT', 'PAYMENTISSUE', 'PAYMENTCLOSED'],
    PAYMENTSENT: ['PAYMENTISSUE', 'PAYMENTRECEIVED'],
    PAYMENTISSUE: ['ACCEPTED', 'PAYMENTCLOSED'],
    PAYMENTRECEIVED: ['PAYMENTISSUE'],
    PAYMENTCLOSED: ['ACCEPTED'],
}