import { SelectOption } from "@powerhousedao/document-engineering/ui";

export const expenseAccountOptions: SelectOption[] = [
    { label: "Grants from Maker DAO", value: "200" },
    { label: "Request Finance IC account", value: "2222" },
    { label: "Interest Income", value: "270" },
    { label: "Activities and Events", value: "3000" },
    { label: "Meals", value: "3001" },
    { label: "Airfare", value: "3002" },
    { label: "Hotels", value: "3003" },
    { label: "Transportation (Uber, Taxi etc)", value: "3004" },
    { label: "Cost of Goods Sold", value: "310" },
    { label: "Advertising", value: "400" },
    { label: "Legal Fees Abroad", value: "4001" },
    { label: "Legal Fees Switzerland", value: "4002" },
    { label: "Finance Team Fees Abroad", value: "4003" },
    { label: "Fnance and Accounting Fees Switzerland", value: "4004" },
    { label: "Software Development Team Fees", value: "4005" },
    { label: "Research Team Fees", value: "4006" },
    { label: "Marketing Team Fees", value: "4007" },
    { label: "Health Care Fees", value: "4008" },
    { label: "Contractor Fees", value: "4009" },
    { label: "Insurance Fees Team", value: "4010" },
    { label: "HR Fees", value: "4011" },
    { label: "Team Bonus", value: "4012" },
    { label: "Refferal Fees", value: "4013" },
    { label: "Depreciation", value: "416" },
    { label: "Freight & Courier", value: "425" },
    { label: "Interest Expense", value: "437" },
    { label: "Office Expenses", value: "453" },
    { label: "Rent", value: "469" },
    { label: "Subscriptions", value: "485" },
    { label: "Bank Revaluations", value: "497" },
    { label: "Unrealised Currency Gains", value: "498" },
    { label: "Realised Currency Gains", value: "499" },
    { label: "Income Tax Expense", value: "505" },
    { label: "Accounts Receivable", value: "610" },
    { label: "Prepayments", value: "620" },
    { label: "Inventory", value: "630" },
    { label: "Software/IT Subscriptions", value: "701" },
    { label: "Office Equipment", value: "710" },
    { label: "Less Accumulated Depreciation on Office Equipment", value: "711" },
    { label: "Computer Equipment", value: "720" },
    { label: "Less Accumulated Depreciation on Computer Equipment", value: "721" },
    { label: "Accounts Payable", value: "800" },
    { label: "Bank Fees", value: "8000" },
    { label: "Gas Fees", value: "8001" },
    { label: "Exchange Fees", value: "8003" },
    { label: "Unpaid Expense Claims", value: "801" },
    { label: "Wages Payable", value: "803" },
    { label: "Sales Tax", value: "820" },
    { label: "Employee Tax Payable", value: "825" },
    { label: "Superannuation Payable", value: "826" },
    { label: "Income Tax Payable", value: "830" },
    { label: "Historical Adjustment", value: "840" },
    { label: "Suspense", value: "850" },
    { label: "Rounding", value: "860" },
    { label: "Tracking Transfers", value: "877" },
    { label: "Owner A Drawings", value: "880" },
    { label: "Owner A Funds Introduced", value: "881" },
    { label: "Loan", value: "900" },
    { label: "Retained Earnings", value: "960" },
    { label: "Owner A Share Capital", value: "970" }
];

export const paymentAccountOptions: SelectOption[] = [
    { label: "Clearing Account USD", value: "USD" },
    { label: "Clearing Account EUR", value: "EUR" },
    { label: "Clearing Account DKK", value: "DKK" },
    { label: "Clearing Account GBP", value: "GBP" },
    { label: "Clearing Account JPY", value: "JPY" },
    { label: "Clearing Account CNY", value: "CNY" },
    { label: "Clearing Account CHF", value: "CHF" },
    { label: "Wallet USDS", value: "USDS" },
    { label: "Wallet DAI", value: "DAI" },
    { label: "Wallet EURe", value: "EURe" },
    { label: "Wallet SKY", value: "SKY" },
    { label: "Wallet MKR", value: "MKR" },
    { label: "Wallet USDC", value: "USDC" },
];